spring.application.name=user-auth-service
server.port=${SERVER_PORT:8081}

#eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=8086

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tripflow_db}
spring.datasource.username=${DB_USERNAME:tripflow_user}
spring.datasource.password=${DB_PASSWORD:tripflow_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

jwt.secret=${JWT_SECRET:tripflow-dev-secret-tripflow-dev-secret-2026-2026}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:2592000000}


# config x swagger
springdoc.api-docs.path=/v3/api-docscs