server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true

          routes:
            - id: booking-service
              uri: lb://booking-service
              predicates:
                - Path=/booking-service/**
              filters:
                - RewritePath=/booking-service/(?<segment>.*), /${segment}

            - id: review-service
              uri: lb://review-service
              predicates:
                - Path=/review-service/**
              filters:
                - RewritePath=/review-service/(?<segment>.*), /${segment}

            - id: itinerary-service
              uri: lb://itinerary-service
              predicates:
                - Path=/itinerary-service/**
              filters:
                - RewritePath=/itinerary-service/(?<segment>.*), /${segment}

            - id: catalog-service
              uri: lb://catalog-service
              predicates:
                - Path=/catalog-service/**
              filters:
                - RewritePath=/catalog-service/(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      access: read-only

springdoc:
  swagger-ui:
    urls:
      - name: Booking Service
        url: http://localhost:8081/v3/api-docs

      - name: Review Service
        url: http://localhost:8082/v3/api-docs

      - name: Itinerary Service
        url: http://localhost:8083/v3/api-docs

      - name: Catalog Service
        url: http://localhost:8084/v3/api-docs