server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            #Route di booking-service e review-service
            - id: booking-service
              uri: lb://booking-service
              predicates:
                - Path=/booking-service/**
              filters:
                - StripPrefix=1

            - id: review-service
              uri: lb://review-service
              predicates:
                - Path=/review-service/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      access: read-only

logging:
  level:
    org.springframework.cloud.gateway: INFO


springdoc:
  swagger-ui:
    # URL di base per accedere alla UI dal gateway
    path: /swagger-ui.html
    urls:
      - name: Itinerary Service
        url: /itinerary/v3/api-docs
      - name: Booking Service
        url: /booking/v3/api-docs
      - name: Catalog Service
        url: /catalog/v3/api-docs
      - name: Review Service
        url: /review/v3/api-docs
      - name: User Auth Service
        url: /user-auth/v3/api-docs