spring.application.name=itinerary-service


#connessione al db postgresql
spring.datasource.url=jdbc:postgresql://localhost:5433/tripflow_db
spring.datasource.username=tripflow_user
spring.datasource.password=tripflow_password

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration