spring.application.name=itinerary-service

# Connessione PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/tripflow_db
spring.datasource.username=tripflow_user
spring.datasource.password=tripflow_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration