spring.application.name=review-service
#eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
server.port=8085

#keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER:http://localhost:9090/realms/tripflow}

spring.datasource.url=jdbc:postgresql://localhost:5432/tripflow_review_db
spring.datasource.username=tripflow_user
spring.datasource.password=tripflow_password
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#RABBITMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#LOGGING
logging.level.com.tripflow.review=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=INFO

tripflow.review.modifica-entro-giorni=30


#config x swagger
springdoc.api-docs.path=/v3/api-docs